### ISSUE TITLE
Сервисы и процедуры, выносимые в API

### ISSUE THREAD

**Issue by pozitronik** [cusodede/dpl#63]
- [ ] Авторизация в DPL.
- [ ] Упрощенная регистрация (Сбор данных о продавце: Паспорт, фото и т.д.).
- [ ] Просмотр профиля пользователя.
- [ ] Просмотр бонусного баланса пользователя со всеми сопутствующими данными => ждём реализации #16
- [ ] История операций.
- [ ] Главный экран, разделы, новости/
- [ ] Верификация (подтверждение менеджеров дилером).
- [ ] Заявление о продаже от менеджера компании вне ДОЛа.
- [ ] Начисление бонусов (ручное начисление) => ждём реализации #16
- [ ] Списание бонусов: моб. Комерция. => ждём реализации #16
- [ ] Планы и выполнение целей.
- [ ] Регистрация контракта (все типы комплектов, е-подпись и бумага, логика черновиков).
- [ ] Список контрактов.
- [ ] Управление тарифом.
- [ ] Регистрация контракта.
- [ ] МНП при регистрации контракта.
- [ ] Список АО.
- [ ] Операции обслуживания.
